### ISSUE TITLE
Kick-Off: Getting started

### ISSUE THREAD

**Issue by mihaeu** [mihaeu/fair-projects#1]
So @FaGerbig und @MarkusRodler was steht alles an? Was wollen wir bis zum 16. Oktober machen/schaffen? (https://github.com/mihaeu/mean-memory/milestones/Kick-Off)

Ich schlage mal vor längere Diskussionen als GitHub Issue umzusetzen und Ergebnisse im GitHub Wiki zu sammeln. Meinungen dazu?

Ausserdem muss ich sagen, dass ich die Entscheidung Skype zu benutzen schon fast wieder bereue. Bilder und Code zu sharen oder leute zu pingen ist einfach lästig bzw. nicht möglich. Ich kann damit leben, aber vielleicht habt ihr ja doch Bock mal Slack auszuprobieren (gibts als App aber auch im Browser). Nur so als Idee :)

Ihr habt ja gesehen, dass das Projekt so steht. Ich habe das einfach mit Git Flow gebootstraped, aber normalles git tuts genauso ich mag nur das automatische branching model.

Also auf `develop` wird entwickelt und alles reingemerged, das darf auch mal instabil sein. `master` ist allerdings immer stable und ist praktisch immer ein sauberer Startpunkt. Da wir drei Leute sind, bieten sich Feature branches an, aber ich denke da hocken wir uns einfach mal zusammen und probieren da rum, was uns am besten passt.

Mein Senf zum eigentlichen Thema, also was ich glaube, was wir bis zum 16. Oktober wissen sollten:
- welchen MEAN Stack verwenden wir?
- wie definieren wir unsere Ziele?
- grober Überblick/`Hello World` der verschiedenen Technologien (Jasmin, AngularJS, MongoDB, Express, Node, ...)
- techn. Infrastruktur festlegen (Build- und Testmanagement, Continuous Integration und Continuous Delivery)
- Entwicklungsumgebung einrichten (nicht nur IDE sondern auch die hundertmillionenen Tools die bei den MEAN Sachen dabei sind ... npm, grunt/gulp, mean)
- ein kleines Kick-Off Dokument das wir vorlegen und abzeichnen lassen können
- vielleicht schon ein paar Backlog Items?

Sonstiges:
- Travis als CI würde sich anbieten, da umsonst und leicht einzurichten und zudem Standard bei open source Javascript Projekten
- Ich habe einen vServer den wir zum deployen benutzen können (oder wir suchen uns einen kostenlosen Service für open source Projekte)
- Wie sollen wir Scrum umsetzen? Ich glaube hier bietet sich ein separates Tool an, dann hat man ein schönes Scrum Board.

Ach ja, kennt ihr ein paar gute Javascript Dojos zum aufwärmen?

Meinungen? Ergänzungen?

**Comment by MarkusRodler** [comment]
Diskussion als Github Issue finde ich unnötig. Wichtige Informationen zu sammeln dagegen essentiell. Die Infos sollten zentral über ein Wiki abrufbar sein.
Also Wiki: Github Wiki
Diskussionen: Skype

Git Flow: Ist klar brauchen wir nicht weiter drüber reden. Kann auch jeder manuell machen wenn ers so lieber hat

Wenns um mehrere Branches geht muss ich fast den Sebastian von IT-Agile zitieren, der gemeint hat, dass man bei agilen Vorgehensweisen sich den Develop-Branch sparen kann und lieber immer stable committen.  Ich weiß, dass du es anders siehst, aber ich finde er hatte da gar nicht so unrecht.

Themenliste für Sprint 0 passt

Travis: Noch nicht benutzt. Kann ich nichts dazu sagen
Scrum: Ok. Würd gern einen PairProgramingDay machen. Sollte auch direkt am Anfang hilfreich sein.

**Comment by mihaeu** [comment]
Ich mache das hier mal zu, die meisten Ergebnisse sind im Wiki.
