### ISSUE TITLE
Projekte anzeigen

### ISSUE THREAD

**Issue by mihaeu** [mihaeu/fair-projects#10]
Projekte anzeigen

**Comment by noichl** [comment]
Aktueller Stand:

Serverseitige implementierungen sind schon vorangeschritten (siehe #5 )

Nächste Todos:
- Angular Service, Controller, Template
- Tests

**Comment by mihaeu** [comment]
Sau gut :+1: 

Ist das nur im Moment so, dass die Projekte separat angezeigt werden? Also man muss ja nochmal auf `Zu den Projekten von ...` klicken, bevor man die Projekte sieht.

**Comment by MarkusRodler** [comment]
Ist mir auch aufgefallen. Denke ich macht mehr Sinn wenn es gleich auf der Detailseite vom Fach angezeigt wird welche Projekte es da gibt. Ansonsten :+1:

**Comment by noichl** [comment]
Mit ngRoute kann man keine nested views machen - dadurch ist es momentan
nicht möglich Fach Details und Projekte gleichzeitig anzuzeigen
Am 06.11.2015 11:05 schrieb "MarkusRodler" notifications@github.com:

**Comment by mihaeu** [comment]
Vielleicht eine bloede Frage, aber was hat das mit den Views zu tun?

Wir koennen doch jedes Model das wir brauchen im Controller laden und an einen einzigen View uebergeben. Oder uebersehe ich da gerade was?

**Comment by MarkusRodler** [comment]
Kurze Anmerkung. Projekte löschen wirft noch einen 500er Fehler. Nur falls du es noch nicht auf dem Radar hast

**Comment by noichl** [comment]
Merci! Hatte ich bei einem der vorherigen Commits zerstört --> Tests müssen her ;)

**Comment by mihaeu** [comment]
E2E Tests sind ja echt schnell geschrieben :)
