### ISSUE TITLE
Codestyle Checks

### ISSUE THREAD

**Issue by mihaeu** [mihaeu/fair-projects#16]
@noichl hat JSCS ja bereits in das Projekt und Grunt integriert, aber wenn ich mich nicht ganz taeusche sind das keine kompletten oder offiziellen Guidelines.

Ist uns das egal oder sollen wir uns welche von Angular oder Google raussuchen?

Wollen wir zwischen Front- und Backend unterscheiden oder die gleichen Guidelines fuer Node und Angular verwenden?

**Comment by MarkusRodler** [comment]
Bin für gleiche Guidelines für Node & Angular

**Comment by noichl** [comment]
@mihaeu  Hast du bei dir lokal die offiziellen Guidelines ausprobiert? 
Wenn sie Server- sowie Clientseitig gut funktionieren habe ich nichts dagegen.

**Comment by mihaeu** [comment]
Ausprobiert ja, aber irgendwie wollten die nicht so wie ich.

Generell passt das was wir jetzt haben schon so ungefaehr, aber die ueberpruefen das noch nicht genau genug, zumindest kommt mir das so vor.

**Comment by mihaeu** [comment]
Ganz cool sehen die [AirBnB Javascript Guidelines](https://github.com/airbnb/javascript) aus. Die sind seit Wochen unter den Trending Javascript Projects auf Github und 25k likes.

Kannst ja mal drueberschauen was du dazu sagst. Die sind relativ tight und das finde ich eigentlich auch gut.

**Comment by MarkusRodler** [comment]
Ja ich seh da auch noch ich Verstöße die eigentlich nicht sein sollten. Hab mir die AirBnB CGLs angesehen und find die mega! :+1:

**Comment by mihaeu** [comment]
Also wenn @noichl und @FaGerbig damit einverstanden sind, dann wuerde ich den Umzug uebernehmen (kann aber gerne auf wer anders machen).

Das ganze hat auch noch den Vorteil, dass ein .jshint File dabei ist, dass noch mehr ueberpruefen kann.

**Comment by noichl** [comment]
Mach das gerne!

**Comment by FaGerbig** [comment]
Einverstanden.

2015-11-09 15:33 GMT+01:00 Marinus Noichl notifications@github.com:

**Comment by mihaeu** [comment]
Fixed in 40438b0
