### ISSUE TITLE
Priorisierung

### ISSUE THREAD

**Issue by mihaeu** [mihaeu/fair-projects#18]
## User Story

```
Als möglicher Teilnehmer
Muss ich einen Projektwunsch priorisieren
```

```
Als möglicher Teilnehmer
Kann ich Prioritäten (1 - Anzahl der Projekte) verändern
```

```
Als möglicher Teilnehmer
Kann ich für jedes Projekt eine Priorität vergeben
```
- Projektteilnahme nach Priorität
- Pro Fach und Teilnehmer kann jede Priorität nur einmal vergeben werden
- Prioritäten werden der Reihe nach vergeben
## Definition of Done
- alle User Stories sind durch Tests abgedeckt
- Validierung auf Client und Server Seite

**Comment by MarkusRodler** [comment]
Priorisierung wird umgesetzt über Reihenfolge die per Drag & Drop geändert werden kann.
Drag & Drop bereits umgesetzt.
Todo: Logik zur Speicherung der Reihenfolge
