### ISSUE TITLE
Grobausarbeitung

### ISSUE THREAD

**Issue by mihaeu** [mihaeu/fair-projects#19]
- zu jedem Unterpunkt ein paar Stichpunkte
- Themen vergeben

**Comment by noichl** [comment]
Um das Wünsch-Dir-Was mal zu starten:
- Konzeptionelle Probleme von DokumentenDatenbanken --> MongoDB
- Security

**Comment by mihaeu** [comment]
Ja, auf jeden Fall beide.

Ich werde definitiv was zu Testbarkeit und Callback-Hell schreiben :smile: 

Aber ich glaube wir sollten das einfach direkt in das [Wiki](https://github.com/mihaeu/fair-projects/wiki/Ausarbeitung) schreiben. Dann muessen wir nicht hin- und her kopieren.

**Comment by mihaeu** [comment]
In der letzten Vorlesung haben wir uns nochmal Feedback vom Dozenten geholt und der meinte wir sollen auf jeden Fall den Fokus auf die Fallstudie legen (und nicht die neuen Technologien ewig lang erklären).

Das spielelt sich in unserem Inhaltsverzeichnis im Moment aber nicht so sehr wieder. Sollen wir vielleicht doch die Fallstudie als Hauptpunkt aufnehmen und anhand dessen die Technologien und wie sie verwendet wurden erklären?

 Input plz @FaGerbig @noichl @MarkusRodler 
Z.B.

### Fallstudie: Fair Projects

#### Einführung, Motivation, Architektur, Mockups, ...

#### Datenbank MongoDB

#### Frontend Framework Angular

....

**Comment by MarkusRodler** [comment]
Er hatte ja  folgende Aufgabenstellung für uns:
Große Unternehmen wie Uber, Red Bull und Netflix setzen
inzwischen Node.js ein. Ein Grund, um einen Blick darauf zu
werfen:
_Der MEAN Stack bietet ein darauf basierendes Webframework Mongo DB, Express, Angular.js, Node.js_
_Beantworten Sie dabei_
- _Funktionsweise und Komponenten von MEAN_
- _Programmiermodell, Werkzeuge, Frameworks, Persistenz_
- _Entwicklungsprozess, Testing, Debugging_
- _Auslieferung, Deployment_
- _Vorteile- und Nachteile gegenüber dem klassischen Ansatz_
- _Use or don‘t use: Für welche Szenarien geeignet?_

Von daher definitiv den Fokus mehr auf die Fallstudie legen und auch mehr den Vergleich ziehen zum tradionellen Aufbau.

**Comment by mihaeu** [comment]
Zitat von Großmeister Rodler:

> Einteilung des Dokuments evtl. ändern

Das sollten wir auf jeden Fall noch machen. Kann das jemand an sich nehmen? @noichl @MarkusRodler @FaGerbig

**Comment by mihaeu** [comment]
Inhaltsverzeichnis steht, Inhalte sollten auch klar sein

zu ...
