### ISSUE TITLE
Task Runner: Grunt vs. Gulp

### ISSUE THREAD

**Issue by mihaeu** [mihaeu/fair-projects#2]
Mal eine kurze Frage:

Wer bevorzugt [Grunt](http://gruntjs.com/) und wer bevorzugt [Gulp](http://gulpjs.com/) als Taskrunner (und wem ist es egal)?

Ich persönlich habe schon viel mit Grunt gearbeitet und mal testweise ein paar Projekte auf Gulp umgestellt und mich nur geärgert. Die Tasks laufen schneller, aber es gibt weniger Plugins und das Konzept sagt mir nicht so zu (piping ist nice, aber sorgt auch für viel Duplikation).

Also für mich:

```
[x] Grunt
[ ] Gulp
[ ] egal
```

Wie sieht es bei euch aus @noichl @MarkusRodler @FaGerbig ?

**Comment by MarkusRodler** [comment]
Grunt hat das bessere Logo. Also Grunt. Ne Spaß. Ich hab zu wenig Erfahrungen mit beiden ums zu bewerten. Hab also nix dagegen bei Grunt zu bleiben

**Comment by mihaeu** [comment]
Ach ja und so als Vergleich http://meanjs.org/ benutzt Grunt und http://mean.io/#!/ benutzt Gulp

**Comment by FaGerbig** [comment]
Von mir aus geht Grunt in Ordnung.

2015-10-17 13:06 GMT+02:00 Michael Haeuslmann notifications@github.com:

**Comment by noichl** [comment]
Ich habe auch noch keine praktische Erfahrung mit beiden Projekten.
Von mir aus dann gerne Grunt.

**Comment by mihaeu** [comment]
Dann wohl Grunt :+1:  Yeah!
