### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by mihaeu** [mihaeu/fair-projects#22]
## User Stories

```
Als Benutzer erkenne ich 
 wenn Änderungen durch mich durchgeführt wurden (erfolgreich wie fehlerhaft).
```
## Akzeptanzkriterien
- Einheitliches Styling auf allen Seiten

**Comment by noichl** [comment]
Erste Anpassungen mit @MarkusRodler  vorgenommen.
Siehe 7546cd2e2dc3ad076652777d109098752509b685
Inputfelder nur im "Editiermodus" ansonsten Ausgabe der Details über <p> Tags

Uns ist aufgefallen dass wir durch die Angabe des Subjectnamens unter den Details überflüssige Informationen, da Redundant mit Überschrift, haben.

**Comment by MarkusRodler** [comment]
Styling ist nun auf allen Seiten einheitlich. Durch die Anpassung ist jQuery denke ich wieder unnötig geworden und kann glaub ich entfernt werden.
