### ISSUE TITLE
Validierung & Security

### ISSUE THREAD

**Issue by mihaeu** [mihaeu/fair-projects#23]
## User Stories

```
Als Benutzer bekomme ich
  bei fehlerhaften Formulareingaben
  eine Fehlermeldung und das betroffene Feld wird hervorgehoben
```

```
Als Benutzer bekomme ich einen Hinweis
  wenn bei Interaktionen mit dem Server Fehler auftreten.
```
## Definition of Done
- Abdeckung der Valdierungsfälle
- Information bei Netzwerkproblemen
- Information bei 500er Fehlermeldungen vom Server die nicht abgefangen werden können (Anwendung im inkonsistenten Zustand)
- API liefert Statuscodes bei Validierungsfehlern
- Tests für Validierungen auf Server-Seite

**Comment by noichl** [comment]
Info zu Statuscodes:
Denkbar wär eine eigene Middleware zu schreiben, die bei entsprechenden Exceptions einen Statuscode + Message liefert und den entsprechenden HTTP-Statuscode setzt.

In den Controllern brauch dann nur eine entsprechende Exception erzeugt und der "next" Funktion übergeben werden.

**Comment by noichl** [comment]
Status Codes wurden angepasst.
Große Validierungsfälle sind in diesem Sprint nicht vorhanden
