### ISSUE TITLE
Welche Angular Version?

### ISSUE THREAD

**Issue by mihaeu** [mihaeu/fair-projects#3]
Gute Frage von Marinus gestern:
- [AngularJS v1.4.7](https://angularjs.org)
- [Angular v2.0.0-alpha](https://angular.io)

Ersteres ist JavaScript, zweiteres ist TypeScript das auf Javascript ES5 kompiliert. Webstorm unterstützt das soweit ganz gut, aber wie es mit Plugins etc. aussieht weiß ich nicht.

Was meint ihr? Ich glaube es gibt genügend neue mehr oder wenig stabile Technologien, als dass man sich noch eine alpha antun muss.

```
[x] AngularJS v1.4.7
[ ] Angular v2.0.0-alpha
[ ] egal
```

Wie sieht es bei euch as @MarkusRodler @noichl @FaGerbig ?

**Comment by MarkusRodler** [comment]
Ich würde auf AngularJS setzen und wenn Zeit bleibt als Beispiel zum präsentieren einen kleinen Teil mit Angular2 austauschen. Das soll ja soweit ohne Probleme gleichzeitig funktionieren. (Wers glaubt^^)

**Comment by noichl** [comment]
Nachdem Angular2 auch mittelfristig wohl noch Alpha/Beta bleibt, und unsere Aufgabe die Bewertung des MEAN-Stacks ist, würde ich stark auf die Verwendung von Angular v1 setzen!

Als Ausblick könnte ich mir Vorstellen die Änderungen durch v2 vorzustellen, und dann auf Auswirkungen im Bezug auf Architektur/Wartbarkeit eingehen, soweit wir dass in diesem Stadium bewerten können. Code ist dazu glaube ich nicht mal nötig.

**Comment by mihaeu** [comment]
@FaGerbig  via Facebook:

> Also, wegen Angular.js Version ists ja denk ich klar das sichs anbietet die 1te, also quasi stable zu nehmen. 

Und damit mache ich hier mal zu und es bleibt wohl bei AngularJS. Ich finde die Idee von Marinus aber auch ganz cool, aber das sehen wir ja am Schluss wie viel Zeit wir fuer die Praesi haben.
