### ISSUE TITLE
Logout logs out everyone

### ISSUE THREAD

**Issue by mihaeu** [mihaeu/fair-projects#32]
Wenn man zwei verschiedene Benutzer gleichzeitig einloggt und dann versucht einen auszuloggen, loggen sich automatisch beide aus.

@noichl Kannst du dir das noch anschauen? Waere cool fuer die Demo.

**Comment by noichl** [comment]
Wenn in einem Browser zwei Fenster gleichzeitig geöffnet werden, und dann zwei user angemeldet werden, wird lediglich die zweite Session gespeichert.

Ist nicht aufgefallen weil die Login Seite auch bei bereits erfolgtem login angezeigt werden konnte.
Wurde mit  811e23a geändert
