### ISSUE TITLE
Projekt erstellen

### ISSUE THREAD

**Issue by mihaeu** [mihaeu/fair-projects#5]
Projekt erstellen mit:
- Titel
- Beschreibung
- Erstelldatum

**Comment by noichl** [comment]
*\* Aktueller Stand: **
- Mongoose Schema für "project" erstellt
- "Subject" Model um "projects" erweitert
- Controller Für das handling von Projekten erstellt
- ExpressRouting in mehrere Middleware Router ausgelagert (erleichtert verschachtelte Routen)
- Angular Service zum abfragen von Projekten erstellen
- Angular Controller + Template zum erstellen von Projekten
- Basis Styling

*\* Nächste Schritte: **
- Erstelldatum hinzufügen
- Validierung
- Erstellen von Tests

*\* Überlegungen: **
- Refactoring Serverseitiger Controller
- Je ein AngularController für List- und Show Usecase?

**Comment by mihaeu** [comment]
Fixed in ed95386
