### ISSUE TITLE
Fach anlegen

### ISSUE THREAD

**Issue by mihaeu** [mihaeu/fair-projects#6]
Fach anlegen
- Titel
- Beschreibung
- Erstellungsdatum
- Autor

**Comment by mihaeu** [comment]
Halb fertig seit 2631888c571d624ee52d612c45199d87df5cec57

Es fehlen noch die weiteren Informationen wie description, dateCreate (bzw. ich weiss gerade nicht wie das der Mongo Standard heisst, den sollte man verwenden) und author.

**Comment by mihaeu** [comment]
Ich habe Markus gerade ueber die Schultern geschaut als er diesen Task implementiert hat, dann habe ich auch gleich was gelernt :).

Wir haben jetzt natuerlich doch direkt `ngRoute` verwenden muessen @noichl :)

Und da `ngRoute` offiziell ist, haben wir das einfach mal `ui-routes` vorgezogen. Wer das noch nicht gesehen hat sollte sich das https://docs.angularjs.org/api/ngRoute/service/$route#example oder das https://docs.angularjs.org/tutorial/step_07 anschauen.

**Comment by MarkusRodler** [comment]
Bei dem Ticket fehlt prinzipiell nur noch der Author. Da wir aber in der ersten Iteration kein Login haben macht es mehr Sinn das Ticket zu schließen und nach Integration von Loginfunktionalität erneut als Ticket anzulegen.
